import type { Metadata } from "next";
import "./globalsLocal.css";
import Footer from "@/components/burgerBliss/footer/Footer";
import Nav from "@/components/burgerBliss/nav/Nav";

export const metadata: Metadata = {
  title: "Burger Bliss",
  description: "Generated by max",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav />

      {children}

      <Footer />
    </>
  );
}
