import type { Metadata } from "next";
import "./globalsLocal.css";
import Nav from "@/components/folliblancMusic/nav/Nav";
import Footer from "@/components/folliblancMusic/footer/Footer";

export const metadata: Metadata = {
  title: "Folliblanc Music",
  description: "Generated by max",
};

export default function TopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav />

      {children}

      <Footer />
    </>
  );
}
