import type { Metadata } from "next";
import "./globalsLocal.css";
import Nav from "@/components/luminousLensPhotography/nav/Nav";
import Footer from "@/components/luminousLensPhotography/footer/Footer";

export const metadata: Metadata = {
  title: "Luminous Lens Photography",
  description: "Generated by max",
};

export default function TopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav />

      {children}

      <Footer />
    </>
  );
}
