import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Julius_Sans_One, Josefin_Sans, Lato, VT323, Rubik } from "next/font/google";

export const metadata: Metadata = {
  title: "Projects",
  description: "Generated by max",
};

const materialSymbolsOutlined = localFont({
  src: "./fonts/MaterialSymbolsOutlined-VariableFont_FILL,GRAD,opsz,wght.ttf",
  variable: "--materialSymbolsOutlined",
});
const materialSymbolsRounded = localFont({
  src: "./fonts/MaterialSymbolsRounded-VariableFont_FILL,GRAD,opsz,wght.ttf",
  variable: "--materialSymbolsRounded",
});
const materialSymbolsSharp = localFont({
  src: "./fonts/MaterialSymbolsSharp-VariableFont_FILL,GRAD,opsz,wght.ttf",
  variable: "--materialSymbolsSharp",
});
const albertExtraBold = localFont({ src: "./fonts/Albert Extrabold.otf", variable: "--albertExtraBold" })
const fakeReceipt = localFont({ src: "./fonts/Fake Receipt.otf", variable: "--fakeReceipt" })

const JuliusSansOne = Julius_Sans_One({ subsets: ["latin"], weight: "400", variable: "--JuliusSansOne" });
const JosefinSans = Josefin_Sans({ subsets: ["latin"], weight: ["300", "400"], variable: "--JosefinSans" });
const lato = Lato({ subsets: ["latin"], weight: ["400"], variable: "--lato" });
const vT323 = VT323({ subsets: ["latin"], weight: ["400"], variable: "--vT323" });
const rubik = Rubik({ subsets: ["latin"], weight: ["400", "500", "700"], variable: "--rubik" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${materialSymbolsOutlined.variable} ${materialSymbolsRounded.variable} ${materialSymbolsSharp.variable} ${JuliusSansOne.variable} ${JosefinSans.variable} ${lato.variable} ${albertExtraBold.variable} ${fakeReceipt.variable} ${vT323.variable} ${rubik.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}